### ISSUE TITLE
Crash on load when using german language and locale

### ISSUE THREAD

**Issue by timlinux** [kartoza/stream_feature_extractor#98]
Using QGIS master:

QGIS-Version | 3.23.0-Master | QGIS-Codeversion | 9c02b8c8f8
-- | -- | -- | --
Qt-Version | 5.15.2
Python-Version | 3.9.7
GDAL-Version | 3.2.2
PROJ-Version | 7.2.1
EPSG-Registraturdatenbankversion | v10.008 (2020-12-16)
GEOS-Version | 3.9.0-CAPI-1.16.2
SQLite-Version | 3.34.1
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.5
QScintilla2-Version | 2.11.5
BS-Version | Fedora 34 (Workstation Edition)
  |   |   |  
Diese QGIS-Kopie schreibt Debugausgaben.
  |   |   |  
Aktive Python-Erweiterungen
Mergin | 2020.5.3
SpreadsheetLayers | 2.0.1
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20

I get a crash when opening the plugin:

```
Konnte Erweiterung 'stream_feature_extractor' nicht laden 

RecursionError: maximum recursion depth exceeded 
Traceback (most recent call last):
  File "/home/timlinux/dev/cpp/QGIS-QtCreator-Build/output/python/qgis/utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "/home/timlinux/dev/cpp/QGIS-QtCreator-Build/output/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/timlinux/.local/share/QGIS/QGIS3/profiles/default/python/plugins/stream_feature_extractor/__init__.py", line 31, in 
    from . import custom_logging  # pylint: disable=relative-import
  File "/home/timlinux/dev/cpp/QGIS-QtCreator-Build/output/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/timlinux/.local/share/QGIS/QGIS3/profiles/default/python/plugins/stream_feature_extractor/custom_logging.py", line 34, in 
    from raven.handlers.logging import SentryHandler
  File "/home/timlinux/dev/cpp/QGIS-QtCreator-Build/output/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/timlinux/.local/share/QGIS/QGIS3/profiles/default/python/plugins/stream_feature_extractor/third_party/raven/__init__.py", line 49, in 
    from raven.base import *  # NOQA
  File "/home/timlinux/dev/cpp/QGIS-QtCreator-Build/output/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/timlinux/.local/share/QGIS/QGIS3/profiles/default/python/plugins/stream_feature_extractor/third_party/raven/base.py", line 37, in 
    from raven.conf.remote import RemoteConfig
  File "/home/timlinux/dev/cpp/QGIS-QtCreator-Build/output/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/timlinux/.local/share/QGIS/QGIS3/profiles/default/python/plugins/stream_feature_extractor/third_party/raven/conf/remote.py", line 36, in 
    DEFAULT_TRANSPORT = discover_default_transport()
  File "/home/timlinux/.local/share/QGIS/QGIS3/profiles/default/python/plugins/stream_feature_extractor/third_party/raven/conf/remote.py", line 18, in discover_default_transport
    from raven.transport.threaded import ThreadedHTTPTransport
  File "/home/timlinux/dev/cpp/QGIS-QtCreator-Build/output/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/timlinux/.local/share/QGIS/QGIS3/profiles/default/python/plugins/stream_feature_extractor/third_party/raven/transport/__init__.py", line 17, in 
    from raven.transport.requests import *  # NOQA
  File "/home/timlinux/dev/cpp/QGIS-QtCreator-Build/output/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/timlinux/.local/share/QGIS/QGIS3/profiles/default/python/plugins/stream_feature_extractor/third_party/raven/transport/requests.py", line 13, in 
    import requests
  File "/home/timlinux/dev/cpp/QGIS-QtCreator-Build/output/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.9/site-packages/requests/__init__.py", line 118, in 
    from . import utils
  File "/home/timlinux/dev/cpp/QGIS-QtCreator-Build/output/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.9/site-packages/requests/utils.py", line 27, in 
    from ._internal_utils import to_native_string
  File "/home/timlinux/dev/cpp/QGIS-QtCreator-Build/output/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.9/site-packages/requests/_internal_utils.py", line 11, in 
    from .compat import is_py2, builtin_str, str
  File "/home/timlinux/dev/cpp/QGIS-QtCreator-Build/output/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.9/site-packages/requests/compat.py", line 29, in 
    import simplejson as json
  File "/home/timlinux/dev/cpp/QGIS-QtCreator-Build/output/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/timlinux/.local/share/QGIS/QGIS3/profiles/default/python/plugins/stream_feature_extractor/third_party/simplejson/__init__.py", line 114, in 
    from .encoder import JSONEncoder, JSONEncoderForHTML
  File "/home/timlinux/dev/cpp/QGIS-QtCreator-Build/output/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/timlinux/.local/share/QGIS/QGIS3/profiles/default/python/plugins/stream_feature_extractor/third_party/simplejson/encoder.py", line 39, in 
    ESCAPE_DCT.setdefault(chr(i), '\\u%04x' % (i,))
  File "/home/timlinux/.local/share/QGIS/QGIS3/profiles/default/python/plugins/stream_feature_extractor/third_party/simplejson/compat.py", line 42, in chr
    return u(chr(s))
  File "/home/timlinux/.local/share/QGIS/QGIS3/profiles/default/python/plugins/stream_feature_extractor/third_party/simplejson/compat.py", line 42, in chr
    return u(chr(s))
  File "/home/timlinux/.local/share/QGIS/QGIS3/profiles/default/python/plugins/stream_feature_extractor/third_party/simplejson/compat.py", line 42, in chr
    return u(chr(s))
  [Previous line repeated 856 more times]
RecursionError: maximum recursion depth exceeded


Python-Version: 3.9.7 (default, Aug 30 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)] 
QGIS-Version: 3.23.0-Master Master, 9c02b8c8f8 

Python-Pfad:
/home/timlinux/dev/cpp/QGIS-QtCreator-Build/output/python
/home/timlinux/.local/share/QGIS/QGIS3/profiles/default/python
/home/timlinux/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/home/timlinux/dev/cpp/QGIS-QtCreator-Build/output/python/plugins
/usr/lib64/python39.zip
/usr/lib64/python3.9
/usr/lib64/python3.9/lib-dynload
/home/timlinux/.local/lib/python3.9/site-packages
/usr/local/lib64/python3.9/site-packages
/usr/local/lib/python3.9/site-packages
/usr/local/lib/python3.9/site-packages/auto_cpufreq-1.0-py3.9.egg
/usr/lib/python3.9/site-packages
/usr/lib64/python3.9/site-packages
/home/timlinux/.local/share/QGIS/QGIS3/profiles/default/python
/home/timlinux/.local/share/QGIS/QGIS3/profiles/default/python/plugins/stream_feature_extractor/third_party
```

**Comment by timlinux** [comment]
Note my locale settings

![image](https://user-images.githubusercontent.com/178003/140810869-d9a7ae1b-7e6a-4c23-af25-ae0c35216abc.png)

**Comment by timlinux** [comment]
Caused by using old version of simplejson
